/* eslint-disable @next/next/no-img-element */
import type { Metadata } from 'next';
import Link from 'next/link';
import '@/css/index.css';

import { IBM_Plex_Sans } from 'next/font/google';

import site from '@/data/site.json';

export const metadata: Metadata = {
  title: 'site.title',
  description: 'Generated by create next app',
};

const ibmPlexSans = IBM_Plex_Sans({
  weight: ['400', '500', '600', '700'],
  style: 'normal',
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  adjustFontFallback: true,
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={ibmPlexSans.className}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🦞</text></svg>"
        />
      </head>
      <body>
        <div className="layout-wrapper">
          <header className="header">
            <div className="header__content">
              <h1 className="site-title">
                <Link href="/">{site.name}</Link>
              </h1>

              {site.headerLinks && (
                <nav className="nav">
                  <ul className="nav__list">
                    {site.headerLinks.map((item) => (
                      <li className="nav-item" key={item.text}>
                        <Link href={item.url} aria-current="page" rel="nooopener noreferrer">
                          {item.text}
                        </Link>
                      </li>
                    ))}
                  </ul>
                </nav>
              )}
            </div>
          </header>

          <main className="main">{children}</main>

          <footer className="footer">
            <div className="footer__content">
              <ul className="hero__social-links">
                {site.socialLinks?.map((item) => {
                  return (
                    <li key={item.text}>
                      <Link href={item.url} target="_blank" rel="nooopener noreferrer">
                        <img className="footer__social--icon" src={item.iconPath} alt={item.text} />
                      </Link>
                    </li>
                  );
                })}

                {site.footerLinks?.map((item) => {
                  return (
                    <li key={item}>
                      <Link href={item} target="_blank" rel="nooopener noreferrer">
                        <img className="footer__social--icon" src={item} alt={item} />
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
